Architecture bootcamp page
Zilola-Nazarova/capstone-project-module-1 pull request #1
Opened 2023-06-24 14:40 UTC by Zilola-Nazarova

## Architecture bootcamp page is created as a capstone project (HTML/CSS & JavaScript)
### General requirements
there are no linter errors;
used correct GitHub flow;
documented the work in a professional way;
### HTML/CSS & JavaScript requirements
followed best practices for HTML & CSS;
followed of best practices for JavaScript;

2023-06-28 16:15 UTC, muneebulrehman requested changes
Hi @Zilola-Nazarova , 

Good job so far! I see you put a lot of effort into this project. However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- No linter errors
- Descriptive PR
- Good commit history
- Great use of javascript to minimize repetitive HTML.
- Good design. 👍

## Required Changes ♻️
_Check the comments under the review._

- [ ] I see you only used one of the font-family (`Lato`) that the original design is using. However, there are two main fonts that the original design is using and you are missing `cocogoose`. You haven't used this font family. I would recommend using this font family in accordance with the provided design.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-28 16:15 UTC, muneebulrehman commented on about.html
> +  </footer>
Same here. Kindly align the footer contents in the center just like in the provided design.
![image](https://github.com/Zilola-Nazarova/capstone-project-module-1/assets/33268927/47550ad3-d3aa-4691-9dfa-9465f641a0aa)

2023-06-28 16:15 UTC, muneebulrehman commented on index.html
> +  </footer>
I would recommend aligning the footer in the center just like in the provided design. 

| Your design  | Provided design |
| ------------- | ------------- |
| ![image](https://github.com/Zilola-Nazarova/capstone-project-module-1/assets/33268927/3955b0dd-fecf-47fa-88f5-446c7036cccb) | ![image](https://github.com/Zilola-Nazarova/capstone-project-module-1/assets/33268927/e5f39d25-85ea-413f-aa00-d6844c3ad48f) |

2023-06-28 16:15 UTC, muneebulrehman commented on index.html
> +    <section id="program" class="program">
I would recommend adding a border effect upon hovering over each article just like in the provided design.
As you can see, when the user hovers over a card, a white border appears around the card.
![image](https://github.com/Zilola-Nazarova/capstone-project-module-1/assets/33268927/45336072-782d-4e38-aad4-c37328452638)

2023-06-28 17:51 UTC, AbelG101 approved these changes
![](https://media.giphy.com/media/YPI7uEvEZr7siYRlZD/giphy.gif)

# Hi @Zilola-Nazarova 👋, 

**Your project is complete!  There is nothing else to say other than... it's time to merge it. 
Congratulations! 🎉 🥳🥇**

## Highlights
- Content is uniquely tailored ✔
- UI is looking amazing✔
- Well-structured files ✔
- All linter checks are passing ✔
- Descriptive PR title with a great summary ✔

## Optional suggestions
- Check the comment below...

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-28 17:51 UTC, AbelG101 commented on styles.css
- [ ] [OPTIONAL] Hey Zilola, I'm really impressed by your design here but I noticed there's a horizontal scroll on the "About page" as shown below this could lead to a bad UX so I'd suggest you fix it.
- Here's how it behaves:
  ![R60DNHqg0G](https://github.com/Zilola-Nazarova/capstone-project-module-1/assets/104968236/8f19aadf-7525-4757-8e79-4f01dff79719)

2023-06-29 07:56 UTC, Zilola-Nazarova commented on styles.css
Thank you for this suggestion @AbelG101!
I didn't even notice this bug because it didn't show me horizontal scrolling in Devtools. I fixed it!

2023-06-29 08:38 UTC, merged